config:
    input_path: "C:\\Users\\vimurali\\ML\\Sentiment-Analysis-Hashtag\\input"
    processed_io_path: "C:\\Users\\vimurali\\ML\\Sentiment-Analysis-Hashtag\\processed_io"
    output_path: "C:\\Users\\vimurali\\ML\\Sentiment-Analysis-Hashtag\\output"
    internal_output_path: "C:\\Users\\vimurali\\ML\\Sentiment-Analysis-Hashtag\\output\\internal_output"
    visualizations_path: "C:\\Users\\vimurali\\ML\\Sentiment-Analysis-Hashtag\\visualizations"
    experimental_output_path: "C:\\Users\\vimurali\\ML\\Sentiment-Analysis-Hashtag\\experimental_logs"
    azureblob_name: "azureml-blobstore-31aeaa24-564c-4aa8-bdf4-fc4b5707bd1b"
    resource_config_path: "C:\\Users\\vimurali\\ML\\Sentiment-Analysis-Hashtag\\config.json"

model_args:
    model: 'rnn'
    batch_size: 1103
    num_epochs: 5
    word2vec_epochs: 1000
    embed_dim: 128
    window_size: 10
    lr: 0.001
    text_max_length: 35
    momentum: 0.8
    lstm_size: 3
    num_layers: 2
    dropout: 0.25
    num_classes: 24 
    target_cols: ['s1','s2','s3','s4','s5', 'w1', 'w2', 'w3', 'w4', 'k1', 'k2', 'k3', 'k4', 'k5', 'k6', 'k7', 'k8', 'k9', 'k10', 'k11', 'k12', 'k13', 'k14', 'k15']
                
preproc_args:
    encoding_type: 'LABEL_ENCODING'
    vectorization_method: 'WC'
    sublinear_tf: True
    norm: 'l2'
    ngram_range_min: 1
    ngram_range_max: 2
    vectorizer_max_features: 5000
    best_k_features: 40
    best_k_words: 5
    apply_stemming: False
    sampling_method: 'SMOTE_SAMPLING'
    sampling_k: 5
    sampling_strategy: 'not majority'
    apply_pseudo_labeling: True
    skip_cols: ['location', 'state']
    train_validation_split: 0.7

validation_args:
    validation_type: 'NORMAL_SPLIT'
    validation_split_share: 0.3
    k: 5